name: CI

on: 
  push:
    branches:    
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: yarn install
      run: |
        yarn install
    - name: yarn test
      run: |
        yarn test 
      env:
        CI: true
      
    - name: yarn build
      run: |
        yarn run build --if-present
    - name: Check for RuboCop
      run: rubocop
    - name: JS Linters
      run: |
          yarn run prettier || yarn run eslintx:all
