# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []
  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false
  # Production depends on precompilation of packs prior to booting for performance.
  compile: false
  # Extract and emit a css file
  extract_css: true

  extensions:
    - .mjs
    - .js
    - .jsx
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .graphql

# Reference: https://webpack.js.org/configuration/dev-server/
dev_server: &dev_server
  https: false
  host: 0.0.0.0
  port: 3035
  public: localhost:3035
  hmr: false
  inline: true
  overlay: true
  compress: true
  disable_host_check: true
  use_local_ip: false
  quiet: false
  pretty: false
  headers:
    'Access-Control-Allow-Origin': '*'
  watch_options:
    ignored: /node_modules/

development:
  <<: *default
  compile: true
  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: false
  dev_server: *dev_server

test:
  <<: *default
  dev_server: *dev_server

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
